[phases.setup]
nixPkgs = ["...", "openssl"]

[phases.build]
cmds = ["npx prisma generate", "npx prisma db push --skip-generate", "npx tsx prisma/seed.ts", "npm run build"]

[start]
cmd = "next start -H 0.0.0.0 --port ${PORT-3000}"
